version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.2
    - 3.11.0
    - 3.11.1
    - 3.9.0
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.6.0
    - 7.7.0
    - 7.8.0
    - 7.9.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@vue/cli-plugin-unit-jest"
    versions:
    - 4.5.12
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.12
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.12
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.12
  - dependency-name: sass-loader
    versions:
    - 11.0.1
  - dependency-name: eslint
    versions:
    - 7.19.0
